#!/bin/sh

# Install deps
rm -r node_modules
npm i

# Compile with tsc
tsc

# Commit to github
today=`date +%Y_%m_%d_%H_%M_%S`
git add . && \
git commit -m "Update at $today" --allow-empty && \
git push