#!/bin/sh

# Install deps
rm -r node_modules
npm i

# Make with rollup
npm run build

# Remove unnecessary types dir (after rollup second compile)
rm -r dist/types

# Commit to github
today=`date +%Y_%m_%d_%H_%M_%S`
git add . && \
git commit -m "Update at $today" --allow-empty && \
git push