#!/bin/sh

# Remove all build files
rm -r dist
rm -r node_modules
rm package-lock.json

# Install deps
npm i

# Compile with tsc
tsc

# Commit to github
today=`date +%Y_%m_%d_%H_%M_%S`
git add . && \
git commit -m "Update at $today" --allow-empty && \
git push